apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: chatapp
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: chinmayapradhan/chatapp-backend:v1
        ports:
        - containerPort: 5001
        env:
        - name: PORT 
          value: "5001"
        - name: NODE_ENV
          value: production
        - name: MONGO_URI
          value: "mongodb://mongo-0.mongo:27017,mongo-1.mongo:27017,mongo-2.mongo:27017/chatapp?replicaSet=rs0"
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              key: jwt 
              name: chatapp-secrets
        resources:
          limits:
            memory: 512Mi
            cpu: 500m
          requests:
            memory: 256Mi
            cpu: 250m
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: chatapp
spec:
  selector:
    app: backend
  ports:
  - protocol: TCP
    port: 5001
    targetPort: 5001
