apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: chatapp
  labels:
    app: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: chinmayapradhan/chatapp-frontend:v1
        ports:
        - containerPort: 80
        env:
        - name: NODE_ENV
          value: production
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: chatapp
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
  - port: 80
    targetPort: 80

